# Uncomment this line to define a global platform for your project
platform :ios, '15.6'

require File.join(File.dirname(__FILE__), 'Flutter', 'podhelper.rb')

install! 'cocoapods', :generate_multiple_pod_projects => true, :incremental_installation => true

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(__FILE__)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end


